export const PUT_USER = "PUT_USER";

export const SET_ACTIVE_CATEGORY = "SET_ACTIVE_CATEGORY";

export const SET_CATEGORIES = "SET_CATEGORIES";

export const SET_CATEGORY_VIDEOS = "SET_CATEGORY_VIDEOS";
